#17. When is the finally block executed? 


# The finally block in Python is always executed, regardless of whether an exception was raised or not in the preceding try block.
# This makes it useful for cleanup actions that must be executed under all circumstances, such as closing files or releasing resources